openapi: 3.0.0
info:
  title: TollBit Services
  version: 0.0.0
tags:
  - name: Auth Tokens
  - name: Tollbit Content
  - name: Get Tollbit Content
paths:
  /dev/v2/content/{contentUrl}:
    get:
      operationId: ContentService_getContent
      parameters:
        - name: contentUrl
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContentResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJSON'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJSON'
        '403':
          description: Access is forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJSON'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJSON'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJSON'
      tags:
        - Tollbit Content
        - Get Tollbit Content
      security:
        - ApiKeyAuth: []
  /tollbit/dev/v2/tokens/aos:
    post:
      operationId: TokensService_createAOSAccessToken
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAOSAccessTokenResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Auth Tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAOSAccessTokenRequest'
      security:
        - ApiKeyAuth: []
  /tollbit/dev/v2/tokens/content:
    post:
      operationId: TokensService_createContentAccessToken
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSubdomainAccessTokenResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Auth Tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubdomainAccessTokenRequest'
      security:
        - ApiKeyAuth: []
  /tollbit/dev/v2/tokens/crawl:
    post:
      operationId: TokensService_createCrawlAccessToken
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCrawlAccessTokenResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Auth Tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCrawlAccessTokenRequest'
      security:
        - ApiKeyAuth: []
components:
  schemas:
    ContentMetadata:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        imageUrl:
          type: string
        author:
          type: string
        published:
          type: string
        modified:
          type: string
    ContentRate:
      type: object
      required:
        - price
        - license
      properties:
        price:
          $ref: '#/components/schemas/RatePrice'
        license:
          $ref: '#/components/schemas/RateLicenseResponse'
    CreateAOSAccessTokenRequest:
      type: object
      required:
        - url
        - userAgent
      properties:
        url:
          type: string
          format: uri
        userAgent:
          type: string
    CreateAOSAccessTokenResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    CreateCrawlAccessTokenRequest:
      type: object
      required:
        - url
        - userAgent
      properties:
        url:
          type: string
          format: uri
        userAgent:
          type: string
    CreateCrawlAccessTokenResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    CreateSubdomainAccessTokenRequest:
      type: object
      required:
        - url
        - userAgent
        - maxPriceMicros
        - currency
        - licenseType
        - licenseCuid
        - format
      properties:
        url:
          type: string
          format: uri
        userAgent:
          type: string
        maxPriceMicros:
          type: integer
          format: int64
        currency:
          type: string
        licenseType:
          type: string
        licenseCuid:
          type: string
        format:
          type: string
          enum:
            - html
            - markdown
    CreateSubdomainAccessTokenResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    Error:
      type: object
    GetContentResponse:
      type: object
      required:
        - content
        - metadata
        - rate
      properties:
        content:
          $ref: '#/components/schemas/PageContent'
        metadata:
          $ref: '#/components/schemas/ContentMetadata'
        rate:
          $ref: '#/components/schemas/ContentRate'
    PageContent:
      type: object
      required:
        - header
        - body
        - footer
      properties:
        header:
          type: string
        body:
          type: string
        footer:
          type: string
    ProblemJSON:
      type: object
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
      additionalProperties: {}
    RateLicensePermission:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    RateLicenseResponse:
      type: object
      required:
        - id
        - licenseType
        - licensePath
        - permissions
        - validUntil
      properties:
        id:
          type: string
        licenseType:
          type: string
        licensePath:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/RateLicensePermission'
        validUntil:
          type: string
          format: date-time
    RatePrice:
      type: object
      required:
        - priceMicros
        - currency
      properties:
        priceMicros:
          type: integer
          format: int64
        currency:
          type: string
    SubdomainAccessToken:
      type: object
      required:
        - type
        - scheme
      properties:
        type:
          type: string
          enum:
            - http
        scheme:
          type: string
          enum:
            - Bearer
      description: |-
        To access content on a TollBit subdomain, you will need an access token. This token is a JWT that is signed by TollBit and includes information about the subdomain and the permissions granted to the token.

        You can obtain the token by calling the TokensService to create a Content Access Token. Once you have the token, you can include it in the Authorization header of your requests to the subdomain.
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: TollbitKey
servers:
  - url: https://gateway.tollbit.com
    variables: {}
